### ISSUE TITLE
onPanEnd not accepting null value? 

### ISSUE THREAD

**Issue by the-unknown-warrior** [sharansingh00002/draw#7]

**Comment by the-unknown-warrior** [comment]
onPanEnd not accepting null value?

**Comment by masterdre093** [comment]
To get pass the null issue i added a isEnd checker. so onPanStart and onPanUpdate i would set it as true. when false it will end the  stroke.

class DrawingPoints {
  Paint paint;
  Offset points;
  bool isEnd; //add this
  DrawingPoints({this.points, this.paint});
}

and in the DrawingPainter use : 
 if (pointsList[x]!.isend) { ... } else {....}
